version: "3.8"

services:
    api-gateway:
        build:
            context: ./api-gateway
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            SPRING_OUTPUT_ANSI_ENABLED: ALWAYS
        depends_on:
            - patient-service

    patient-service:
        build:
            context: ./patient-service
            dockerfile: Dockerfile
        ports:
            - "8081:8081"
        environment:
            SPRING_PROFILES_ACTIVE: "dev"
            SPRING_OUTPUT_ANSI_ENABLED: ALWAYS
            SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
        depends_on:
            - kafka

    billing-service:
        build:
            context: ./billing-service
            dockerfile: Dockerfile
        ports:
            - "8082:8082"
            - "9002:9002"
        environment:
            SPRING_PROFILES_ACTIVE: ""
            SPRING_OUTPUT_ANSI_ENABLED: ALWAYS
        depends_on:
            - kafka

    analytics-service:
        build:
            context: ./analytics-service
            dockerfile: Dockerfile
        ports:
            - "8083:8083"
        environment:
            SPRING_PROFILES_ACTIVE: ""
            SPRING_OUTPUT_ANSI_ENABLED: ALWAYS
            SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
        depends_on:
            - kafka

    kafka:
        image: bitnami/kafka:latest
        environment:
            - KAFKA_ENABLE_KRAFT=yes
            - KAFKA_CFG_NODE_ID=0
            - KAFKA_CFG_PROCESS_ROLES=controller,broker
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
            - KAFKA_KRAFT_CLUSTER_ID=kraft-cluster
        ports:
            - "9092:9092"
            - "9094:9094"
