server:
    port: 8080

spring:
    cloud:
        gateway:
            routes:
                - id: patient-service-route
                  uri: http://patient-service:8081
                  predicates:
                      - Path=/api/patients/**
                  filters:
                      - StripPrefix=1

                - id: api-docs-patient-route
                  uri: http://patient-service:8081
                  predicates:
                      - Path=/api-docs/patients
                  filters:
                      - RewritePath=/api-docs/patients,/v3/api-docs
